export const products = [
  {
    name: "2 3/4 KURUVI",
    description: "Kuruvi cracker, each Pkt has 5 pcs",
    price: 14,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "3 1/2 LAKSHMI",
    description: "Lakshmi cracker, each Pkt has 5 pcs",
    price: 20,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "4'' LAKSHMI",
    description: "Lakshmi cracker, each Pkt has 5 pcs",
    price: 26,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "4'' DELUXE LAKSHMI",
    description: "Deluxe Lakshmi cracker, each Pkt has 5 pcs",
    price: 50,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "4'' DELUXE GOLD LAKSHMI",
    description: "Deluxe Gold Lakshmi cracker, each Pkt has 5 pcs",
    price: 56,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "5'' MEGA DELUXE",
    description: "Mega Deluxe cracker, each Pkt has 5 pcs",
    price: 64,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "5'' MEGA RIDER",
    description: "Mega Rider cracker, each Pkt has 5 pcs",
    price: 80,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "DON (10 PCS)",
    description: "Don crackers, 10 pcs in a box",
    price: 600,
    quantityMetric: "1 Box",
    categoryId: 1,
  },
  {
    name: "2 SOUND",
    description: "Sound crackers, each Pkt has 5 pcs",
    price: 64,
    quantityMetric: "1 Pkt",
    categoryId: 1,
  },
  {
    name: "28 CHORSA",
    description: "Chorsa crackers, each Pkt has 5 pcs",
    price: 28,
    quantityMetric: "1 Pkt",
    categoryId: 2,
  },
  {
    name: "28 GIANT",
    description: "Giant crackers, each Pkt has 5 pcs",
    price: 48,
    quantityMetric: "1 Pkt",
    categoryId: 2,
  },
  {
    name: "56 GIANT",
    description: "Giant crackers, each Pkt has 5 pcs",
    price: 100,
    quantityMetric: "1 Pkt",
    categoryId: 2,
  },
  {
    name: "100 WALA",
    description: "Wala crackers, each Pkt has 5 pcs",
    price: 70,
    quantityMetric: "1 Pkt",
    categoryId: 2,
  },
  {
    name: "200 WALA",
    description: "Wala crackers, each Pkt has 5 pcs",
    price: 140,
    quantityMetric: "1 Pkt",
    categoryId: 2,
  },
  {
    name: "24 DELUXE",
    description: "Deluxe crackers, each Pkt has 5 pcs",
    price: 100,
    quantityMetric: "1 Pkt",
    categoryId: 3,
  },
  {
    name: "50 DELUXE",
    description: "Deluxe crackers, each Pkt has 5 pcs",
    price: 300,
    quantityMetric: "1 Pkt",
    categoryId: 3,
  },
  {
    name: "100 DELUXE",
    description: "Deluxe crackers, each Pkt has 5 pcs",
    price: 600,
    quantityMetric: "1 Pkt",
    categoryId: 3,
  },
  {
    name: "1000 WALA [N]",
    description: "Wala crackers, each pcs has 1 unit",
    price: 280,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "1000 WALA CLASSIC",
    description: "Classic crackers, each pcs has 1 unit",
    price: 400,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "2000 WALA [N]",
    description: "Wala crackers, each pcs has 1 unit",
    price: 560,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "2000 WALA CLASSIC",
    description: "Classic crackers, each pcs has 1 unit",
    price: 800,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "5000 WALA CLASSIC",
    description: "Classic crackers, each pcs has 1 unit",
    price: 1500,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "5000 WALA PREMIUM",
    description: "Premium crackers, each pcs has 1 unit",
    price: 2000,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "10000 WALA CLASSIC",
    description: "Classic crackers, each pcs has 1 unit",
    price: 3000,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "10000 WALA PREMIUM",
    description: "Premium crackers, each pcs has 1 unit",
    price: 4000,
    quantityMetric: "1 Pcs",
    categoryId: 4,
  },
  {
    name: "RED BIJILI (50 PCS)",
    description: "Bijili crackers, 50 pcs in a pkt",
    price: 32,
    quantityMetric: "1 Pkt",
    categoryId: 5,
  },
  {
    name: "RED BIJILI (100 PCS)",
    description: "Bijili crackers, 100 pcs in a pkt",
    price: 60,
    quantityMetric: "1 Pkt",
    categoryId: 5,
  },
  {
    name: "STRIPPED BIJILI (100 PCS)",
    description: "Stripped Bijili crackers, 100 pcs in a pkt",
    price: 70,
    quantityMetric: "1 Pkt",
    categoryId: 5,
  },
  {
    name: "BULLET BOMB",
    description: "Bullet bomb, each box has 10 pcs",
    price: 56,
    quantityMetric: "1 Box",
    categoryId: 6,
  },
  {
    name: "ATOM BOMB",
    description: "Atom bomb, each box has 10 pcs",
    price: 108,
    quantityMetric: "1 Box",
    categoryId: 6,
  },
  {
    name: "HYDRO BOMB",
    description: "Hydro bomb, each box has 10 pcs",
    price: 160,
    quantityMetric: "1 Box",
    categoryId: 6,
  },
  {
    name: "KING OF KING BOMB",
    description: "King of King bomb, each box has 10 pcs",
    price: 220,
    quantityMetric: "1 Box",
    categoryId: 6,
  },
  {
    name: "CLASSIC BOMB",
    description: "Classic bomb, each box has 10 pcs",
    price: 240,
    quantityMetric: "1 Box",
    categoryId: 6,
  },
  {
    name: "DTX BOMB",
    description: "DTX bomb, each box has 10 pcs",
    price: 460,
    quantityMetric: "1 Box",
    categoryId: 6,
  },
  {
    name: "MOTTERA STICK",
    description: "Mottera stick candle, each box has 10 pcs",
    price: 104,
    quantityMetric: "1 Box",
    categoryId: 7,
  },
  {
    name: "NAVRAGA CANDLE",
    description: "Navraga candle, each box has 10 pcs",
    price: 320,
    quantityMetric: "1 Box",
    categoryId: 7,
  },
  {
    name: "SEE LEASER CANDLE",
    description: "See laser candle, each box has 10 pcs",
    price: 320,
    quantityMetric: "1 Box",
    categoryId: 7,
  },
  {
    name: "GREEN LEASER CANDLE",
    description: "Green laser candle, each box has 10 pcs",
    price: 320,
    quantityMetric: "1 Box",
    categoryId: 7,
  },
  {
    name: "SELFIE STICK",
    description: "Selfie stick candle, each box has 10 pcs",
    price: 320,
    quantityMetric: "1 Box",
    categoryId: 7,
  },
  {
    name: "ROCKET BOMB",
    description: "Rocket bomb, each box has 10 pcs",
    price: 140,
    quantityMetric: "1 Box",
    categoryId: 8,
  },
  {
    name: "LUNIK ROCKET",
    description: "Lunik rocket, each box has 10 pcs",
    price: 320,
    quantityMetric: "1 Box",
    categoryId: 8,
  },
  {
    name: "WHISTLING ROCKET",
    description: "Whistling rocket, each box has 10 pcs",
    price: 400,
    quantityMetric: "1 Box",
    categoryId: 8,
  },
  {
    name: "GROUND CHAKKAR BIG (10 PCS)",
    description: "Big ground chakkars, each box has 10 pcs",
    price: 100,
    quantityMetric: "1 Box",
    categoryId: 9,
  },
  {
    name: "COLOUR SWIRLS (SPL)",
    description: "Special color swirls, each box has 10 pcs",
    price: 200,
    quantityMetric: "1 Box",
    categoryId: 9,
  },
  {
    name: "COLOUR SWIRLS (DELUXE)",
    description: "Deluxe color swirls, each box has 10 pcs",
    price: 300,
    quantityMetric: "1 Box",
    categoryId: 9,
  },
  {
    name: "SPINNER SPECIAL",
    description: "Special spinners, each box has 10 pcs",
    price: 360,
    quantityMetric: "1 Box",
    categoryId: 9,
  },
  {
    name: "SPINNER DLX",
    description: "Deluxe spinners, each box has 10 pcs",
    price: 420,
    quantityMetric: "1 Box",
    categoryId: 9,
  },
  {
    name: "DANCING WHEEL",
    description: "Dancing wheel, each box has 10 pcs",
    price: 200,
    quantityMetric: "1 Box",
    categoryId: 10,
  },
  {
    name: "WHISTLING DELUX",
    description: "Deluxe whistling wheel, each box has 10 pcs",
    price: 220,
    quantityMetric: "1 Box",
    categoryId: 10,
  },
  {
    name: "FLOWER POTS SMALL (10 PCS)",
    description: "Small flower pots, each box has 10 pcs",
    price: 120,
    quantityMetric: "1 Box",
    categoryId: 11,
  },
  {
    name: "FLOWER POTS BIG (10 PCS)",
    description: "Big flower pots, each box has 10 pcs",
    price: 160,
    quantityMetric: "1 Box",
    categoryId: 11,
  },
  {
    name: "FLOWER POTS SPL (10 PCS)",
    description: "Special flower pots, each box has 10 pcs",
    price: 200,
    quantityMetric: "1 Box",
    categoryId: 11,
  },
  {
    name: "FLOWER POTS ULTRA SPL (10 PCS)",
    description: "Ultra special flower pots, each box has 10 pcs",
    price: 220,
    quantityMetric: "1 Box",
    categoryId: 11,
  },
  {
    name: "FLOWER POTS ASHOKA (10 PCS)",
    description: "Ashoka flower pots, each box has 10 pcs",
    price: 250,
    quantityMetric: "1 Box",
    categoryId: 11,
  },
  {
    name: "COLOUR KOTI",
    description: "Color koti, each box has 10 pcs",
    price: 440,
    quantityMetric: "1 Box",
    categoryId: 12,
  },
  {
    name: "COLOUR KOTI DLX",
    description: "Deluxe color koti, each box has 10 pcs",
    price: 680,
    quantityMetric: "1 Box",
    categoryId: 12,
  },
  {
    name: "COLOUR COTI SUPER DLX",
    description: "Super deluxe color coti, each box has 10 pcs",
    price: 220,
    quantityMetric: "1 Box",
    categoryId: 12,
  },
  {
    name: "POP CORN",
    description: "Pop corn, each pcs has 1 unit",
    price: 320,
    quantityMetric: "1 Pcs",
    categoryId: 13,
  },
  {
    name: "AUTOM RAIN",
    description: "Autom rain, each pcs has 1 unit",
    price: 300,
    quantityMetric: "1 Pcs",
    categoryId: 13,
  },
  {
    name: "PEACOCK FEATHER",
    description: "Peacock feather, each box has 10 pcs",
    price: 260,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "COLOUR RAIN",
    description: "Color rain, each box has 10 pcs",
    price: 260,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "PAPPU SHOWER",
    description: "Pappu shower, each box has 10 pcs",
    price: 260,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "BUTTER FLY",
    description: "Butter fly, each box has 10 pcs",
    price: 160,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "LOONEY TUNES",
    description: "Looney tunes, each box has 10 pcs",
    price: 200,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "DRONE",
    description: "Drone, each box has 10 pcs",
    price: 240,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "HELICOPTER",
    description: "Helicopter, each box has 10 pcs",
    price: 200,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "PAMPARAM",
    description: "Pamparam, each box has 10 pcs",
    price: 200,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "CHIN CHAN TRY COLOUR",
    description: "Chin Chan try color, each box has 10 pcs",
    price: 280,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "WATER SHOWER",
    description: "Water shower, each box has 10 pcs",
    price: 300,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "WATER RAIN",
    description: "Water rain, each box has 10 pcs",
    price: 300,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "PHOTOFLASH",
    description: "Photoflash, each box has 10 pcs",
    price: 180,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "ROYAL COLOUR",
    description: "Royal color, each box has 10 pcs",
    price: 260,
    quantityMetric: "1 Box",
    categoryId: 13,
  },
  {
    name: "MONEY BANK",
    description: "Money bank, each box has 10 pcs",
    price: 400,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "MERRY GO MERRY",
    description: "Merry go merry, each box has 10 pcs",
    price: 540,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "COLOUR COLLETION",
    description: "Color collection, each box has 10 pcs",
    price: 360,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "ALL STAR ROBO",
    description: "All star robo, each box has 10 pcs",
    price: 320,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "MAGIC PEACOCK 5 IN 1",
    description: "Magic peacock 5 in 1, each pcs has 1 unit",
    price: 400,
    quantityMetric: "1 Pcs",
    categoryId: 15,
  },
  {
    name: "MAGIC PEACOCK 3 IN 1",
    description: "Magic peacock 3 in 1, each pcs has 1 unit",
    price: 400,
    quantityMetric: "1 Pcs",
    categoryId: 15,
  },
  {
    name: "FIRE EGG",
    description: "Fire egg, each box has 10 pcs",
    price: 340,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "COLOUR SMOKE",
    description: "Color smoke, each box has 10 pcs",
    price: 360,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "MICKEY POPE",
    description: "Mickey pope, each box has 10 pcs",
    price: 320,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "FOUNTAION COLOUR",
    description: "Foundation color, each box has 10 pcs",
    price: 300,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "CHOTTU TRY COLOUR",
    description: "Chottu try color, each box has 10 pcs",
    price: 400,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "FOUNTAION COLOUR",
    description: "Foundation color, each box has 10 pcs",
    price: 360,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "SIREN (3 PCS)",
    description: "Siren, each box has 3 pcs",
    price: 380,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "LOTUS WHEEL",
    description: "Lotus wheel, each box has 10 pcs",
    price: 380,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "PLASH GUN",
    description: "Plash gun, each box has 10 pcs",
    price: 400,
    quantityMetric: "1 Box",
    categoryId: 14,
  },
  {
    name: "BAD BOY",
    description: "Bad boy, each box has 10 pcs",
    price: 1000,
    quantityMetric: "1 Box",
    categoryId: 16,
  },
  {
    name: "WHISTLE PODU",
    description: "Whistle podu, each box has 10 pcs",
    price: 480,
    quantityMetric: "1 Box",
    categoryId: 16,
  },
  {
    name: "BADA PEACOCK",
    description: "Bada peacock, each pcs has 1 unit",
    price: 1000,
    quantityMetric: "1 Pcs",
    categoryId: 16,
  },
  {
    name: "CRACKLING FOUNTAIN",
    description: "Crackling fountain, each box has 10 pcs",
    price: 800,
    quantityMetric: "1 Box",
    categoryId: 16,
  },
  {
    name: "1 1/2'' TWINLING STAR",
    description: "Twinling star, each box has 10 pcs",
    price: 48,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "4'' TWINLING STAR",
    description: "Twinling star, each box has 10 pcs",
    price: 140,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "7 CM ELECTRIC",
    description: "7 cm electric sparkler, each box has 10 pcs",
    price: 20,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "7 CM COLOUR",
    description: "7 cm color sparkler, each box has 10 pcs",
    price: 24,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "7 CM GREEN",
    description: "7 cm green sparkler, each box has 10 pcs",
    price: 24,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "7 CM RED",
    description: "7 cm red sparkler, each box has 10 pcs",
    price: 28,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "10 CM ELECTRIC",
    description: "10 cm electric sparkler, each box has 10 pcs",
    price: 36,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "10 CM COLOUR",
    description: "10 cm color sparkler, each box has 10 pcs",
    price: 40,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "10 CM GREEN",
    description: "10 cm green sparkler, each box has 10 pcs",
    price: 44,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "10 CM RED",
    description: "10 cm red sparkler, each box has 10 pcs",
    price: 52,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "12 CM ELECTRIC",
    description: "12 cm electric sparkler, each box has 10 pcs",
    price: 52,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "12 CM COLOUR",
    description: "12 cm color sparkler, each box has 10 pcs",
    price: 56,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "12 CM GREEN",
    description: "12 cm green sparkler, each box has 10 pcs",
    price: 60,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "12 CM RED",
    description: "12 cm red sparkler, each box has 10 pcs",
    price: 66,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "15 CM ELECTRIC",
    description: "15 cm electric sparkler, each box has 10 pcs",
    price: 84,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "15 CM COLOUR",
    description: "15 cm color sparkler, each box has 10 pcs",
    price: 92,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "15 CM GREEN",
    description: "15 cm green sparkler, each box has 10 pcs",
    price: 100,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "15 CM RED",
    description: "15 cm red sparkler, each box has 10 pcs",
    price: 108,
    quantityMetric: "1 Box",
    categoryId: 17,
  },
  {
    name: "SINGLE PIECE",
    description: "Single piece fancy item, each box has 10 pcs",
    price: 100,
    quantityMetric: "1 Box",
    categoryId: 18,
  },
  {
    name: "SPEED ( 3 PCS )",
    description: "Speed fancy item, each box has 3 pcs",
    price: 400,
    quantityMetric: "1 Box",
    categoryId: 18,
  },
  {
    name: "SINGLE PIECE",
    description: "Single piece fancy item, each box has 1 pc",
    price: 200,
    quantityMetric: "1 PCS",
    categoryId: 18,
  },
  {
    name: "MARVEL WHITE ( 6 COLOUR MIX )",
    description: "Marvel white fancy item, each box has 1 pc",
    price: 300,
    quantityMetric: "1 PCS",
    categoryId: 18,
  },
  {
    name: "FROZEN ( 3 VARITY MIX )",
    description: "Frozen fancy item, each box has 3 varieties, 10 pcs",
    price: 520,
    quantityMetric: "1 Box",
    categoryId: 18,
  },
  {
    name: "5 STAR ( 7 VARITY MIX )",
    description: "5 Star fancy item, each box has 7 varieties, 10 pcs",
    price: 640,
    quantityMetric: "1 Box",
    categoryId: 18,
  },
  {
    name: "PLAY BOY ( 5 VARITY MIX )",
    description: "Play Boy fancy item, each box has 5 varieties, 1 pc",
    price: 600,
    quantityMetric: "1 PCS",
    categoryId: 18,
  },
  {
    name: "ASTRA ( 4 VARITY MIX )",
    description: "Astra fancy item, each box has 4 varieties, 10 pcs",
    price: 1240,
    quantityMetric: "1 Box",
    categoryId: 18,
  },
  {
    name: "CARTOON NETWORK",
    description: "Cartoon Network fancy item, each box has 2 pcs",
    price: 1700,
    quantityMetric: "1 Box",
    categoryId: 18,
  },
  {
    name: "TEJAS EXPRESS",
    description: "Tejas Express fancy item, each box has 2 pcs",
    price: 2200,
    quantityMetric: "1 Box",
    categoryId: 18,
  },
  {
    name: "HIP HOP ( 3 VARITY MIX )",
    description: "Hip Hop item, each box has 3 varieties, 10 pcs",
    price: 700,
    quantityMetric: "1 Box",
    categoryId: 19,
  },
  {
    name: "7 SHOTS ( 5 PCS )",
    description: "7 shots item, each box has 5 pcs",
    price: 180,
    quantityMetric: "1 Box",
    categoryId: 19,
  },
  {
    name: "12 SHOTS WINNER",
    description: "12 shots winner item, each box has 1 pc",
    price: 400,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "12 SHOTS RIDER",
    description: "12 shots rider item, each box has 1 pc",
    price: 320,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "15 SHOTS",
    description: "15 shots item, each box has 1 pc",
    price: 620,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "25 SHOTS",
    description: "25 shots item, each box has 1 pc",
    price: 800,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "30 SHOTS",
    description: "30 shots item, each box has 1 pc",
    price: 900,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "30 SHOTS ( BHARAT KI DANCE )",
    description: "30 shots Bharat Ki Dance item, each box has 1 pc",
    price: 1000,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "CRAZY 50 SHOTS",
    description: "Crazy 50 shots item, each box has 1 pc",
    price: 1600,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "60 SHOT",
    description: "60 shot item, each box has 1 pc",
    price: 1800,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "60 SHOT ( DIWALE )",
    description: "60 shot Diwale item, each box has 1 pc",
    price: 2000,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "120 SHOT",
    description: "120 shot item, each box has 1 pc",
    price: 3600,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "120 SHOT GOOGLE",
    description: "120 shot Google item, each box has 1 pc",
    price: 4000,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "240 SHOT ( GREAT INDIAN )",
    description: "240 shot Great Indian item, each box has 1 pc",
    price: 8000,
    quantityMetric: "1 PCS",
    categoryId: 19,
  },
  {
    name: "10 X 10 SHOTS",
    description: "10 x 10 shots item, each box has 1 box",
    price: 9000,
    quantityMetric: "1 Box",
    categoryId: 19,
  },
  {
    name: "40 ITEMS BOX",
    description: "Gift box containing 40 items, no discount",
    price: 900,
    quantityMetric: "1 Box",
    categoryId: 20,
  },
  {
    name: "50 ITEMS BOX",
    description: "Gift box containing 50 items, no discount",
    price: 1400,
    quantityMetric: "1 Box",
    categoryId: 20,
  },
  {
    name: "FAMILY PACK BOX",
    description: "Family pack box containing assorted items",
    price: 4000,
    quantityMetric: "1 Box",
    categoryId: 20,
  },
];
